### ISSUE TITLE
Expansion inside another expansion

### ISSUE THREAD

**Issue by kovvalsky** [texttheater/produce#41]
Is smth similar to this `var = %{'' if lang == 'en' else '-a %{align}'}` possible to achieve?

For example, one might want to allow an additional argument for the script in a recipe if the target file is non-English. In the example, non-English files are additionally prepanded with alignments. 
```
[out/p%{part}/d%{doc_id}/%{lang}.ids_words]
dep.ids      = out/p%{part}/d%{doc_id}/%{lang}.ids
dep.align    = out/p%{part}/d%{doc_id}/%{lang}.align
dep.words    = out/p%{part}/d%{doc_id}/%{lang}.words 
opt_arg      = %{'' if lang == 'en' else '-a %{align}'}
recipe       = put_together  %{ids}  %{words}  %{opt_arg}     
```

**Comment by texttheater** [comment]
Instead of `var = %{'' if lang == 'en' else '-a %{align}'}`, use `var = %{'' if lang == 'en' else '-a ' + align}`. It works because rule attributes (`align` in this case) are just Python variables, and things between curly braces are just Python expressions.

**Comment by kovvalsky** [comment]
Thanks. I thought about this option. This means that it is intuitive. :)
