### ISSUE TITLE
Update on pypi

### ISSUE THREAD

**Issue by LoicGrobol** [texttheater/produce#48]
Hi, thanks for merging #47 so quickly, do you think you could update the version on pypi, too? Also if you'd like, I'd be happy to help set up a way to do these releases automatically. With what I did for https://github.com/LoicGrobol/scorch you just have to push a tag on git and travis takes care of building the release and uploading it on pypi.

Sorry for the noise from my part these days, I have just started using produce in my workflow and I'm still flexing its muscles. Conversely if there are issues you'd like me to work on, just say the word!

**Comment by texttheater** [comment]
Hi, yes, that automated workflow sounds good! I'd appreciate your help with setting it up.

**Comment by LoicGrobol** [comment]
Great ! Working on it

**Comment by texttheater** [comment]
Hi @LoicGrobol, did you get a chance to look into this?

**Comment by LoicGrobol** [comment]
Hey, not only had I totally forgotten about it (really sorry for that), but I think the way I thought of it is now somewhat obsolete given the availability of new github actions. I will try to look into this next week, sorry again for the delay

**Comment by texttheater** [comment]
That would be awesome, thank you!

**Comment by LoicGrobol** [comment]
Hi @texttheater, I am working on this now. Could you give me access to the project on test.pypi.org so I can test the workflow?

**Comment by texttheater** [comment]
Sure, done!
